apiVersion: v1
kind: Service
metadata:
  name: posts-node-port-srv
spec:
  type: NodePort
  selector:
    app: posts
  ports:
    - name: posts-http-port
      protocol: TCP
      port: 4000
      targetPort: 4000
