### Retrieve movies
GET http://localhost:3000/movies

### Retrieve movie by id
GET http://localhost:3000/movies/fbb05a1e-70f1-11ee-9ff6-0242ac110002

### Retrieve by genre
GET http://localhost:3000/movies?genre=crime

### Post a movie
POST http://localhost:3000/movies
Content-Type: application/json

{
  "title": "The Godfather",
  "year": 1975,
  "director": "Francis Ford Coppola",
  "duration": 175,
  "genre": [
    "crime",
    "drama"
  ],
  "poster": "https://i.imgur.com/Uzvny9I.jpg"
}

### This is an invalid POST
POST http://localhost:3000/movies
Content-Type: application/json

{
  "nope": "hehe"
}

### Update a movie
PATCH http://localhost:3000/movies/12874d30-7108-11ee-9ff6-0242ac110002
Content-Type: application/json

{
  "year": 1993
}

### Delete a movie
DELETE http://localhost:3000/movies/efb56499-7107-11ee-9ff6-0242ac110002
